format = "$directory$git_branch$git_status$cmd_duration$line_break$character"

[character]
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold #f97316)"

[cmd_duration]
min_time = 2000
style = "bold #30363d"

[directory]
style = "bold cyan"
truncate_to_repo = true
truncation_length = 3

[git_branch]
style = "bold #f97316"
symbol = " "

[git_status]
modified = "[~$count](yellow)"
staged = "[+$count](green)"
style = "bold #f97316"
untracked = "[?$count](blue)"
